apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golden-path-api
  namespace: gitops
  labels:
    app.kubernetes.io/managed-by: platform-engineering-lab
  annotations:
    platform.engineering-lab/chart-revision: "3787c00564553253be81d41ce5ec2b567d4f6d5d"
    platform.engineering-lab/image-source-revision: "e4cbf6cfa1817fe8dede7eb80d75bb94131163b2"
    platform.engineering-lab/image-digest: "sha256:e12b5835af642aa1ea153ed27b4aa0481c1cf03e434702106bf57dfeeb7a70cf"
    platform.engineering-lab/evidence-file: ../evidence/golden-path-api.json
spec:
  project: platform-apps
  source:
    repoURL: https://github.com/Rano1000/platform-engineering-lab.git
    targetRevision: "3787c00564553253be81d41ce5ec2b567d4f6d5d"
    path: charts/golden-path-api
    helm:
      releaseName: golden-path
      valuesObject:
        image:
          repository: ghcr.io/rano1000/golden-path-api
          tag: ""
          digest: "sha256:e12b5835af642aa1ea153ed27b4aa0481c1cf03e434702106bf57dfeeb7a70cf"
          revision: "e4cbf6cfa1817fe8dede7eb80d75bb94131163b2"
          pullPolicy: IfNotPresent
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
