apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "golden-path-api.fullname" . }}-allow-approved-ingress
  labels:
    {{- include "golden-path-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "golden-path-api.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: platform-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.metricsTest.namespace }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.metricsTest.podLabels | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8080
