apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "golden-path-api.fullname" . }}
  labels:
    {{- include "golden-path-api.labels" . | nindent 4 }}
automountServiceAccountToken: false
